/*! test-project - (c) 2026 dps200205. All rights reserved. Unauthorized copying prohibited. */
const s='http://localhost:3000/api';const i=[{name:'JavaScript',icon:'fab fa-js-square'},{name:'Python',icon:'fab fa-python'},{name:'React',icon:'fab fa-react'},{name:'Vue',icon:'fab fa-vuejs'},{name:'Node.js',icon:'fab fa-node-js'},{name:'HTML5',icon:'fab fa-html5'},{name:'CSS3',icon:'fab fa-css3-alt'},{name:'Git',icon:'fab fa-git-alt'},{name:'Docker',icon:'fab fa-docker'},{name:'Database',icon:'fas fa-database'},];const t=[{title:'艺术地球',description:'基于 Three.js 的交互式 3D 地球可视化项目，展示全球建筑风格。',tags:['Three.js','WebGL','JavaScript'],color:'#6c5ce7',emoji:'🌍',},{title:'AI 智能助手',description:'集成多种大语言模型的智能对话助手，支持代码生成和文档分析。',tags:['Python','FastAPI','LLM'],color:'#00b894',emoji:'🤖',},{title:'云端笔记',description:'支持 Markdown 编辑、实时同步的跨平台笔记应用。',tags:['React','Node.js','MongoDB'],color:'#e17055',emoji:'📝',},];const n={years:5,projects:30,tech:15};function renderSkills(){const p=document.getElementById('skillsGrid');if(!p)return;p.innerHTML=i.map((skill)=>`
        <div class="skill-card fade-in">
            <i class="${skill.icon}"></i>
            <span>${skill.name}</span>
        </div>`).join('');}function renderProjects(){const p=document.getElementById('projectsGrid');if(!p)return;p.innerHTML=t.map((proj)=>`
        <div class="project-card fade-in">
            <div class="project-banner" style="background:${proj.color}">${proj.emoji}</div>
            <div class="project-info">
                <h3>${proj.title}</h3>
                <p>${proj.description}</p>
                <div class="project-tags">
                    ${proj.tags.map((t) => `<span class="tag">${t}</span>`).join('')}
                </div>
            </div>
        </div>`).join('');}function animateNumber(el,d,o){let c=0;const g=d/(o/16);const m=setInterval(()=>{c+=g;if(c>=d){el.textContent=d;clearInterval(m);}else{el.textContent=Math.floor(c);}},16);}function startStatsAnimation(){const r=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){animateNumber(document.getElementById('statYears'),n.years,1000);animateNumber(document.getElementById('statProjects'),n.projects,1500);animateNumber(document.getElementById('statTech'),n.tech,1200);r.disconnect();}});},{threshold:0.5});const e=document.getElementById('about');if(e)r.observe(e);}function initTheme(){const l=document.getElementById('themeToggle');const u=localStorage.getItem('theme')||'dark';if(u==='light'){document.documentElement.setAttribute('data-theme','light');l.innerHTML='<i class="fas fa-sun"></i>';}l.addEventListener('click',()=>{const a=document.documentElement.getAttribute('data-theme')==='light';document.documentElement.setAttribute('data-theme',a?'dark':'light');l.innerHTML=a?'<i class="fas fa-moon"></i>':'<i class="fas fa-sun"></i>';localStorage.setItem('theme',a?'dark':'light');});}function showToast(b){const h=document.getElementById('h');h.textContent=b;h.classList.add('show');setTimeout(()=>h.classList.remove('show'),3000);}function initContactForm(){const f=document.getElementById('contactForm');if(!f)return;f.addEventListener('submit',async(e)=>{e.preventDefault();const data={name:document.getElementById('name').value,email:document.getElementById('email').value,message:document.getElementById('message').value,};try{const v=await fetch(`${s}/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),});if(v.ok){showToast('消息已发送，感谢联系！');f.reset();}else{showToast('发送失败，请稍后重试');}}catch{showToast('消息已记录（离线模式）');f.reset();}});}document.addEventListener('DOMContentLoaded',()=>{renderSkills();renderProjects();startStatsAnimation();initTheme();initContactForm();});